const DISHES = [
    {
        "name": "Buffalo chicken",
        "cuisine": "American",
        "difficulty": "medium",
        "serving": 4,
        "vegan": false,
        "healthy": false,
        "moreeffort": true,
        "discription": "These spicy wings are ideal party food for any celebration. The chicken is brined to make it extra juicy and the smoky sweetness of the sauce adds heat.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/buffalo-chicken"
    },
    {
        "name": "Pecan pie with maple cream",
        "cuisine": "American",
        "difficulty": "hard",
        "serving": 12,
        "vegan": true,
        "healthy": false,
        "moreeffort": false,
        "discription": "Wow family and friends with this golden pecan pie and silky, sweet maple cream. Making the pastry is optional, but the recipe is particularly good.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/pecan-pie-maple-cream"
    },
    {
        "name": "Hot gumbo dip",
        "cuisine": "American",
        "difficulty": "easy",
        "serving": 6,
        "vegan": false,
        "healthy": true,
        "moreeffort": false,
        "discription": "Serve this smoky, chunky veg gumbo dip with Tom Kerridge's Southern-fried prawns. It makes an excellent condiment for an American-themed platter.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/hot-gumbo-dip"
    },
    {
        "name": "Japanese ramen noodle soup",
        "cuisine": "Japanese",
        "difficulty": "easy",
        "serving": 4,
        "vegan": false,
        "healthy": false,
        "moreeffort": false,
        "discription": "Use chicken, noodles, spinach, sweetcorn and eggs to make this moreish Japanese noodle soup, for when you crave something comforting yet light and wholesome.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/japanese-ramen-noodle-soup"
    },
    {
        "name": "Japanese-style bento box",
        "cuisine": "Japanese",
        "difficulty": "medium",
        "serving": 1,
        "vegan": false,
        "healthy": false,
        "moreeffort": true,
        "discription": "This Asian-inspired lunchbox with mackerel sushi, edamame beans and fresh fruit will keep you going all afternoon.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/japanese-style-bento-box"
    },
    {
        "name": "Japanese rice:gohan",
        "cuisine": "Japanese",
        "difficulty": "easy",
        "serving": 4,
        "vegan": false,
        "healthy": true,
        "moreeffort": false,
        "discription": "No Japanese meal is complete without gohan – fluffy, slightly sticky rice. Top this versatile food with pickles, spring onions, nori or katsuobushi flakes.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/japanese-rice-gohan"
    },
    {
        "name": "Miso soup",
        "cuisine": "Japanese",
        "difficulty": "easy",
        "serving": 4,
        "vegan": true,
        "healthy": true,
        "moreeffort": false,
        "discription": "Make your own miso soup with soft cubes of tofu, crunchy curls of seaweed and aromatic spring onions. Enjoy it as a starter or as a snack.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/miso-soup"
    },
    {
        "name": "Tonkatsu pork",
        "cuisine": "Japanese",
        "difficulty": "medium",
        "serving": 4,
        "vegan": false,
        "healthy": false,
        "moreeffort": false,
        "discription": "Rustle up a Japanese feast and try this succulent pork loin, coated, fried and drizzled with our easiest ever Tonkatsu sauce. Save leftovers to make katsudon.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/tonkatsu-pork"
    },
    {
        "name": "Veggie okonomiyaki",
        "cuisine": "Japanese",
        "difficulty": "easy",
        "serving": 2,
        "vegan": true,
        "healthy": true,
        "moreeffort": false,
        "discription": "Supercharge your diet with this vegetarian okonomiyaki with eggs, cabbage, pak choi and spring onions. It makes a healthy, low calorie lunch option.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/veggie-okonomiyaki"
    },
    {
        "name": "Arancini balls",
        "cuisine": "Italian",
        "difficulty": "hard",
        "serving": 18,
        "vegan": false,
        "healthy": false,
        "moreeffort": true,
        "discription": "Adapt these arancini rice balls to your liking: add fresh herbs, sundried tomatoes or chopped ham. You can also make the balls from leftover cold risotto.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/arancini-balls"
    },
    {
        "name": "Braised rabbit pappardelle",
        "cuisine": "Italian",
        "difficulty": "hard",
        "serving": 5,
        "vegan": false,
        "healthy": false,
        "moreeffort": true,
        "discription": "Slow-cook rich game into a delicious ragu to serve with ribbon pasta - stock and wine will keep the lean meat moist.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/braised-rabbit-pappardelle"
    },
    {
        "name": "Focaccia",
        "cuisine": "Italian",
        "difficulty": "easy",
        "serving": 4,
        "vegan": true,
        "healthy": false,
        "moreeffort": true,
        "discription": "Make a simple, homemade version of this classic Italian bread. Serve our rosemary focaccia alongside pasta dishes or enjoy with green salads.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/focaccia"
    },
    {
        "name": "Fig & prosciutto pizzettas",
        "cuisine": "Italian",
        "difficulty": "medium",
        "serving": 6,
        "vegan": false,
        "healthy": true,
        "moreeffort": false,
        "discription": "Impress when entertaining with these mini pizzas topped with creamy mozzarella, sweet fruit and salty Italian ham.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/tonkatsu-pork"
    },
    {
        "name": "Gnocchi with parsley, butter & samphire",
        "cuisine": "Italian",
        "difficulty": "medium",
        "serving": 4,
        "vegan": true,
        "healthy": true,
        "moreeffort": true,
        "discription": "Pass on the pasta and try making your own potato gnocchi - forage for samphire to make a fresh and frugal meat-free main.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/gnocchi-parsley-butter-samphire"
    },
    {
        "name": "Courgette & quinoa-stuffed peppers",
        "cuisine": "Mediterranean",
        "difficulty": "easy",
        "serving": 4,
        "vegan": true,
        "healthy": true,
        "moreeffort": false,
        "discription": "Take just 5 ingredients and create this healthy Mediterranean-style vegetarian bake for a low-calorie, low-fat supper.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/courgette-quinoa-stuffed-peppers"
    },
    {
        "name": "Mediterranean potato salad",
        "cuisine": "Mediterranean",
        "difficulty": "medium",
        "serving": 4,
        "vegan": true,
        "healthy": true,
        "moreeffort": false,
        "discription": "Swap a mayonnaise base for cherry tomatoes, olives, roasted red peppers and fresh Italian herbs in this low-fat salad.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/mediterranean-potato-salad-0"
    },
    {
        "name": "Caponata",
        "cuisine": "Mediterranean",
        "difficulty": "easy",
        "serving": 8,
        "vegan": true,
        "healthy": true,
        "moreeffort": false,
        "discription": "A quintessentially Sicilian veggie dish of aubergines, tomatoes, raisins, capers and pine nuts - serve with toasted ciabatta.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/caponata"
    },
    {
        "name": "Spinach with chilli & lemon crumbs",
        "cuisine": "Mediterranean",
        "difficulty": "medium",
        "serving": 4,
        "vegan": true,
        "healthy": true,
        "moreeffort": false,
        "discription": "Wilt fresh greens then serve with crispy breadcrumbs, chilli and garlic for a low-fat, healthy side dish.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/spinach-chilli-lemon-crumbs"
    },
    {
        "name": "Mussels with tomatoes & chilli",
        "cuisine": "Mediterranean",
        "difficulty": "medium",
        "serving": 2,
        "vegan": true,
        "healthy": true,
        "moreeffort": true,
        "discription": "This spicy seafood recipe makes a fantastic meal for two but can be easily increased for a stylish dinner party starter.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/mussels-tomatoes-chilli"
    },
    {
        "name": "Mediterranean slices",
        "cuisine": "Mediterranean",
        "difficulty": "hard",
        "serving": 4,
        "vegan": true,
        "healthy": false,
        "moreeffort": true,
        "discription": "Keep sliced roasted peppers, puff pastry and artichokes in the freezer and you'll never be stuck for a smart starter again.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/mediterranean-slices"
    },
    {
        "name": "Thai chicken cakes with sweet chilli sauce",
        "cuisine": "Thai",
        "difficulty": "medium",
        "serving": 3,
        "vegan": false,
        "healthy": false,
        "moreeffort": false,
        "discription": "A light and healthy supper that's a great variation on the chicken theme. Works well as a starter or a main – just serve with sweet chilli sauce.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/thai-chicken-cakes-sweet-chilli-sauce"
    },
    {
        "name": "Fragrant Thai prawns",
        "cuisine": "Thai",
        "difficulty": "easy",
        "serving": 4,
        "vegan": false,
        "healthy": true,
        "moreeffort": false,
        "discription": "Add subtle Thai flavours to seafood in Curtis Stone's prawn recipe.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/fragrant-thai-prawns"
    },
    {
        "name": "Next level pad Thai",
        "cuisine": "Thai",
        "difficulty": "easy",
        "serving": 2,
        "vegan": false,
        "healthy": false,
        "moreeffort": true,
        "discription": "Take the classic pad Thai to new levels, adding king prawns and tofu, pickled turnip and tamarind paste - a dish for two that's packed with flavour.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/next-level-pad-thai"
    },
    {
        "name": "Thai chicken and sweet potato soup",
        "cuisine": "Thai",
        "difficulty": "hard",
        "serving": 2,
        "vegan": false,
        "healthy": false,
        "moreeffort": false,
        "discription": "A smooth and and spicy chicken soup with a vibrant colour that's packed full of Asian aromatics.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/thai-chicken-and-sweet-potato-soup"
    },
    {
        "name": "Thai green chicken curry",
        "cuisine": "Thai",
        "difficulty": "medium",
        "serving": 4,
        "vegan": false,
        "healthy": false,
        "moreeffort": false,
        "discription": "Making your own fragrant curry paste takes some special Asian ingredients and a little time but you'll taste the difference.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/thai-green-chicken-curry-0"
    },
    {
        "name": "Lamb kleftiko",
        "cuisine": "Greek",
        "difficulty": "hard",
        "serving": 6,
        "vegan": false,
        "healthy": false,
        "moreeffort": true,
        "discription": "Seal a leg of lamb in a parcel then roast it long and slow with garlic, lemon and herbs, and potatoes to soak up the delicious juices.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/lamb-kleftiko"
    },
    {
        "name": "Greek-style roast fish",
        "cuisine": "Greek",
        "difficulty": "easy",
        "serving": 2,
        "vegan": false,
        "healthy": true,
        "moreeffort": false,
        "discription": "Oven-bake white fish fillets with potatoes, tomatoes and herbs for a healthy and gluten-free weeknight dinner.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/greek-style-roast-fish"
    },
    {
        "name": "Spiced feta with watermelon salsa",
        "cuisine": "Greek",
        "difficulty": "easy",
        "serving": 2,
        "vegan": true,
        "healthy": false,
        "moreeffort": false,
        "discription": "Treat this salty Greek cheese a little differently by coating a chunk with cumin and coriander, then serving with a light and fruity salsa.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/mediterranean-slices"
    },
    {
        "name": "Gigantes plaki",
        "cuisine": "Greek",
        "difficulty": "easy",
        "serving": 4,
        "vegan": true,
        "healthy": false,
        "moreeffort": false,
        "discription": "Satisfying and superhealthy, enjoy at room temperature as part of a meze, or on top of toasted sourdough.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/gigantes-plaki"
    },
    {
        "name": "Greek lamb with orzo",
        "cuisine": "Greek",
        "difficulty": "hard",
        "serving": 6,
        "vegan": false,
        "healthy": false,
        "moreeffort": true,
        "discription": "Entertaining doesn't have to equal stress, this spruced up one-pot is perfect for people with little time for preparation.",
        "receiptLink": "https://www.bbcgoodfood.com/recipes/greek-lamb-orzo"
    }
]